	
<div class="modal fade" id="modal-edit-user" tabindex="-1" role="dialog" aria-labelledby="modal-label-user-edit">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1 class="modal-title" id="modal-label-user-edit">Modifier votre compte</h1>
      </div>
      <div class="modal-body">
		<h2>Informations personnelles</h2>
		<form method="POST">
			<div class="form-group">
				<label for="first_name">Prénom</label>
				<input type="text" class="form-control" id="first_name" name="first_name" value="<?=htmlentities($first_name)?>">
			</div>
			<div class="form-group">
				<label for="last_name">Nom</label>
				<input type="text" class="form-control" id="last_name" name="last_name" value="<?=htmlentities($last_name)?>">
			</div>
			<div class="form-group">
		    	<label for="email">Email</label>
		   	 	<input type="email" class="form-control" id="email" name="email" value="<?=htmlentities($email)?>">
		 	</div>
		 	<div class="form-group">
		    	<label for="phone">Téléphone</label>
		   	 	<input type="text" class="form-control" id="phone" name="phone" value="<?=htmlentities($phone)?>">
		 	</div>
		 	<div class="form-group">
		    	<label for="avatar">Avatar</label>
		    	<input type="file" id="avatar" name="avatar">
		    	<p class="help-block">Intégrer votre avatar.</p>
		 	</div>
			<button type="submit" class="btn btn-success" name="action" value="edit_user">Modifier les paramètres</button>
		</form>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-edit-secure" tabindex="-1" role="dialog" aria-labelledby="modal-label-secure-edit">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1 class="modal-title" id="modal-label-secure-edit">Modifier votre compte</h1>
      </div>
      <div class="modal-body">
		<h2>Paramètres de sécurité</h2>
		<form method="POST">
			<div class="form-group">
				<label for="login">Login</label>
				<input type="text" class="form-control" id="login" name="login" value="<?=htmlentities($_SESSION['login'])?>">
			</div>
			<div class="form-group">
				<label for="old_password">Mot de passe actuel</label>
				<input type="password" class="form-control" id="old_password" name="old_password" placeholder="Mot de passe actuel">
			</div>
			<div class="form-group">
				<label for="new_password">Nouveau mot de passe</label>
				<input type="password" class="form-control" id="new_password" name="new_password" placeholder="Nouveau mot de passe">
			</div>
			<div class="form-group">
				<label for="new_password_repeat">Retaper votre nouveau mot de passe</label>
				<input type="password" class="form-control" id="new_password_repeat" name="new_password_repeat" placeholder="Retaper votre nouveau mot de passe">
			</div>
			<button type="submit" class="btn btn-success" name="action" value="edit_secure">Modifier les paramètres</button>
		</form>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
  		</div>
    </div>
  </div>
</div>