<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <span class="logo"><a href="index.php"><img src="public/images/bm-logo.jpg" alt="Bistrot Moderne" class="img-logo"></a></span> -->
      <span><a class="navbar-brand" href="#">Bistrot moderne</a></span>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="register">Register <span class="sr-only">(current)</span></a></li> -->
		    <li><a href="list_plat">Accueil</a></li>
        <li><a href="account">Mon compte</a></li>
        <li><a href="list_command">Mes commandes</a></li>
    <!-- <li><a href="list_user">list user</a></li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><p class="navbar-text">Bienvenue <b><?=htmlentities($_SESSION['login'])?></b></p></li>
        <li>
          <form method= "post">
            <button type="submit" class="btn btn-warning navbar-btn" name="action" value="logout">Se déconnecter</button>
          </form>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- <div class="container header-img">
  <a href="#"><img src="public/images/bm-logo.jpg" alt="Bistrot Moderne"></a>
</div> -->

<?php require('apps/login.php'); ?>