<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bistrot moderne</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="register">Register <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><a href="account">Account</a></li> -->
		    <!-- <li><a href="list_plat">list plat</a></li>
        <li><a href="list_command">list command</a></li>
        <li><a href="list_user">list user</a></li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><button type="button" class="btn btn-primary navbar-btn" data-toggle="modal" data-target="#modal-login">Connexion</button></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- <div class="container">
  <a href="#"><img src="public/images/bm-logo.jpg" alt="Bistrot Moderne"></a>
</div>
 -->


<?php require('apps/login.php'); ?>
<?php require('apps/register.php'); ?>
