<div class="col-xs-12 col-md-6">
	<div class="row">
		<div class="col-xs-12 col-sm-4">
			<div class="img-plat">
				<img src="http://toquedechoc.com/wp-content/uploads/2015/03/photo-salade1.jpg" alt="salade" class="img-thumbnail img-plat">
			</div>
		</div>
		<div class="col-xs-12 col-sm-8">
			<form method="POST">
				<?php require('apps/btn_plat.php');?>
				<div class="plat">
					<p class="jour"><?=htmlentities($jour)?></p>
					<?php require('apps/content_plat.php') ?> 
				</div>
			</form>
			<p>COMMANDE PAR : </p>
		</div>
		<div class="col-xs-12">
			<?php require('apps/list_user.php') ?>
			<br><br>
		</div>
	</div>
</div>
