<?php

// var_dump($_SESSION); 
// var_dump(password_hash('login1',PASSWORD_BCRYPT));
?>

<div class="modal fade" id="modal-register" tabindex="-1" role="dialog" aria-labelledby="modal-label-register">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1 class="modal-title" id="modal-label-register">Inscription</h1>
      </div>
      <div class="modal-body">

		<form method="POST">
			<div class="form-group">
				<label for="login">Login</label>
				<input type="text" class="form-control" id="login" name="login" placeholder="Login">
			</div>
			<div class="form-group">
				<label for="first_name">Prénom</label>
				<input type="text" class="form-control" id="first_name" name="first_name" placeholder="Prénom">
			</div>
			<div class="form-group">
				<label for="last_name">Nom</label>
				<input type="text" class="form-control" id="last_name" name="last_name" placeholder="Nom">
			</div>
			<div class="form-group">
		    	<label for="email">Email</label>
		   	 	<input type="email" class="form-control" id="email" name="email" placeholder="Email">
		 	</div>
		 	<div class="form-group">
		    	<label for="phone">Téléphone</label>
		   	 	<input type="text" class="form-control" id="phone" name="phone" placeholder="Téléphone">
		 	</div>
		 	<div class="form-group">
		    	<label for="avatar">Avatar</label>
		    	<input type="file" id="avatar" name="avatar">
		    	<p class="help-block">Intégrer votre avatar.</p>
		 	</div>
			<div class="form-group">
				<label for="password1">Mot de passe</label>
				<input type="password" class="form-control" id="password1" name="password1" placeholder="Mot de passe">
			</div>
			<div class="form-group">
				<label for="password2">Retaper votre mot de passe</label>
				<input type="password" class="form-control" id="password2" name="password2" placeholder="Retaper votre mot de passe">
			</div>
			<button type="submit" class="btn btn-success" name="action" value="register">Créer votre compte</button>
		</form>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>











