<form method="POST" action="" class="ticketform">
	<input type="hidden" name="status" value="<?=$statut?>">
	<div class="btn-group btn-group-vertical" role="group">
		<div class="btn-group" role="group">
			<input type="hidden" name="ticket_id" value="<?=htmlentities($ticket_id)?>" ></input>
			<button type="submit" class="btn-xs btn btn-danger glyphicon glyphicon-trash" value="delete_ticket" name="action"></button>
		</div>
	</div>
</form>