<div class="col-xs-12 section special">

	<h2>Tickets :</h2>
	<div class="row">
	<?php require('apps/error.php'); ?>
		<article class="col-xs-12 col-sm-4">
			<div class="row">
				<div class="col-xs-10">
					<h2>A FAIRE</h2>
				</div>
				<div class="col-xs-2">
					<form method="post" action="index.php?page=tickets&traitement=traitement_affichecreer">
				        <button name="affichecreer" value="true">+</button>
					</form>
				</div>
				<?php require('apps/ticket_afaire.php') ?>
			</div>
		</article>
		<article class="col-xs-12 col-sm-4">
			<div class="row">
				<h2 class='col-xs-12'>EN COURS</h2>
				<?php require('apps/ticket_encours.php') ?>
			</div>
		</article>
		<article class="col-xs-12 col-sm-4">
			<div class="row">
				<h2 class='col-xs-12'>FAIT</h2>
				<?php require('apps/ticket_fait.php') ?>
			</div>
		</article>
	</div>

</div>