<div class="col-xs-12">
	<form method="post">
		<p>
        	<!-- <input type="hidden" name="count" value="<?=$count?>" > -->
    		<input type="hidden" name="status" value="create" >
            <!-- <input type="text" name="user_id" value="<?=htmlentities($_SESSION['login'])?>"> -->
    		<input type="text" name="title" placeholder="Mon titre">
        	<input type="text" name="content" placeholder="Mon contenu">
        	<input type="URL" name="img" placeholder="URL de mon image">
        	<button type="submit" name="action" value="creat_ticket">CRÉER</button><br><br>
		</p>
	</form>
</div>