<li class="list-group-item ticket">
    <div class="media">
        <form method="POST">
            <div class="media-left">
            <div>
                <?=htmlentities($login)?>
            </div>
                <center>
                    <?=htmlentities($ticket_id)?>
                </center>
                 <!--    <a target="_blank" href="index.php" alt="img">
                        <img class="media-object" src="url_img" alt="image" style="max-height:64px;max-width:64px;">
                    </a> -->
            </div>
            <div class="media-body">
                <input type="text" name="title" placeholder="Mon titre" value="<?=htmlentities($ticket['title'])?>">
                <input type="text" name="content" placeholder="Mon contenu" value="<?=htmlentities($ticket['content'])?>">
                <input type="URL" name="img" placeholder="URL de mon image" value="<?=htmlentities($ticket['url_img'])?>">
            </div>
            <div class="ticketform">
                <input type="hidden" name="ticket_id" value="<?=htmlentities($ticket_id)?>">
                <button type="submit" class="glyphicon glyphicon-ok" value="valid_ticket" name="action"></button>
            </div>
        </form>
    </div>
</li>
