<div class="col-xs-5 chkbox">
	<form method="post" action="index.php?page=tickets&traitement=traitement_ticket">
   		<input type="hidden" name="count" value="<?=$count?>"/>
   		<button type="submit" name="etat" value="aediter">ed</button>  
   		<button type="submit" name="etat" value="nodisplay">sp</button>  
   		<button type="submit" name="etat" value="encours">></button>  
   		<input type="hidden" name="contenu" value="<?=$tickets[$count]['contenu']?>" />
	</form>
</div>