<form method="POST" action="" class="ticketform">
	<input type="hidden" name="ticket_id" value="<?=htmlentities($ticket_id)?>" ></input>
	<input type="hidden" name="statut" value="<?=htmlentities($ticket_statut)?>" ></input>
	<input type="hidden" name="status" value="<?=$statut?>">
	<button type="submit" class="btn-xs btn btn-success glyphicon glyphicon-ok" value="next_ticket" name="action"></button>
</form>