<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="index.php">LivredOr</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li><a href="index.php?page=home">Home</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?=$_SESSION['login']?> <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="index.php?page=logout">Logout</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>