<h1>Inscription</h1>
<form method="POST">
	<div class="form-group">
		<label for="login">Login</label>
		<input type="text" class="form-control" id="login" name="login" placeholder="Login">
	</div>
	<div class="form-group">
		<label for="password1">Password</label>
		<input type="password" class="form-control" id="password1" name="password1" placeholder="Password">
	</div>
	<div class="form-group">
		<label for="password2">Retype Password</label>
		<input type="password" class="form-control" id="password2" name="password2" placeholder="Retype Password">
	</div>
	<button type="submit" class="btn btn-default" name="action" value="register">S'enregistrer</button>
</form>