<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>LivredOr</title>
		<link rel="stylesheet" type="text/css" href="public/styles/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="public/styles/bootstrap-theme.min.css">
		<link rel="stylesheet" type="text/css" href="public/styles/style.css">
		<script type="text/javascript" src="public/scripts/jquery.min.js"></script>
		<script type="text/javascript" src="public/scripts/bootstrap.min.js"></script>
		<script type="text/javascript" src="public/scripts/script.js"></script>
	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/content.php'); ?>
		<?php require('apps/footer.php'); ?>
	</body>
</html>